// <auto-generated />
namespace EF6CodeFirstSamples.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class changenameisrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changenameisrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201402270553058_change name is required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
